### ISSUE TITLE
Error logs after running run.sh

### ISSUE THREAD

**Issue by fobabs** [Michal2SAB/Bitcoin-Stealer#51]
I get this error when I run the run.sh script file.
**OS**: Ubuntu 22.04
**Node version**: 18.1.0
**coinkey package installed**: 3.0.0
```
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at CoinKey.get (/home/fobabs/Desktop/hacks/crypto/Bitcoin-Stealer/Linux/node_modules/eckey/lib/eckey.js:65:33)
    at CoinKey.get (/home/fobabs/Desktop/hacks/crypto/Bitcoin-Stealer/Linux/node_modules/coinkey/lib/coinkey.js:45:27)
    at generate (/home/fobabs/Desktop/hacks/crypto/Bitcoin-Stealer/Linux/generator.js:22:25)
    at Object.<anonymous> (/home/fobabs/Desktop/hacks/crypto/Bitcoin-Stealer/Linux/generator.js:51:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.1.0
```

**Comment by fobabs** [comment]
I just got this fixed. It happen to be the node version. I tried a much more stable version like v16.15.1 LTS and it worked.
